name: 'Action Setup Bash'
description: 'Our recommended setup for Bash'

runs:
  using: 'composite'
  steps:
    - shell: bash --login {0}
      run: cat "${GITHUB_ACTION_PATH}/bash_profile.sh" >> ~/.bash_profile
